### ISSUE TITLE
Null pointer when authenticating as guest

### ISSUE THREAD

**Issue by dkocher** [hierynomus/smbj#792]
Attempting to authenticate as guest using `AuthenticationContext.guest()` results in an exception 
```
Caused by: java.lang.NullPointerException
	at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKey(SMBSessionBuilder.java:324)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKeys(SMBSessionBuilder.java:290)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:174)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:152)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:119)
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:197)
```

The server is running `SMB_3_1_1` (Windows Server 2022)

**Comment by hierynomus** [comment]
@dkocher Which version? I fixed a similar bug for anonymous authentication in v0.12.2, and I thought I had checked guest then also.

**Comment by dkocher** [comment]
> @dkocher Which version? I fixed a similar bug for anonymous authentication in v0.12.2, and I thought I had checked guest then also.

Running `0.12.2`.

**Comment by hierynomus** [comment]
@dkocher Which authenticator are you using?

**Comment by dkocher** [comment]
> @dkocher Which authenticator are you using?

This is using `NtlmAuthenticator`.

**Comment by karthik-119** [comment]
Even, I'm facing the same Nullpointer exception when trying with anonymous login:
```
java.lang.NullPointerException
  at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKey(SMBSessionBuilder.java:324)
  at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKeys(SMBSessionBuilder.java:290)
  at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:174)
  at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:152)
  at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:119)
  at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:202)
```
It is happening after upgrade to smbj library 0.12.2 and my target server Windows 11, I've tried to allow insecure guest logons as well in my Local group policy editor.

Is there any update on the issue, whether if it's server configuration issue or bug in the actual code?

**Comment by dkocher** [comment]
@karthik-119 points out this may be a regression of 4633709a.

**Comment by hierynomus** [comment]
@dkocher @karthik-119 Can you try with the fix from https://github.com/hierynomus/smbj/pull/800?

**Comment by bubbleguuum** [comment]
I tested and:

- I get the crash in first post with published 0.12.2
- I do not get the crash using current git smbj as of the date of this post **without #800 applied**

So that issue has already been fixed by a commit post v0.12.2 it seems.

**Comment by hierynomus** [comment]
@bubbleguuum Now that's even weirder, as Git doesn't show any change which could have anything to do with that on the current `master` branch 🤔

**Comment by bubbleguuum** [comment]
Yes please disregard, I did my testing wrong (was actually using v0.11.1 instead of git master!).
Will do it again properly with the PR applied.

**Comment by bubbleguuum** [comment]
Still crashing using master git + the 1 line PR.
Check that everything is correct this time, with even a logged "LALA" line just before the `if (ctx.sessionKey != null) {` line change:

```
smb: resolved FOOBAR -> 192.168.1.157
        PacketEncryptor  I  Initialized PacketEncryptor with Cipher << AES_128_CCM >>
             Connection  I  Successfully connected to: 192.168.1.157
           SMBShareInfo  I  smb: \\FOOBAR\: NegotiatedProtocol{dialect=SMB_3_0_2, maxTransactSize=8388608, maxReadSize=8388608, maxWriteSize=8388608}
      SMBSessionBuilder  I  LALA
           SMBShareInfo  W  java.lang.NullPointerException: Attempt to invoke interface method 'byte[] javax.crypto.SecretKey.getEncoded()' on a null object reference
                         W      at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKey(SMBSessionBuilder.java:326)
                         W      at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKeys(SMBSessionBuilder.java:294)
                         W      at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:176)
                         W      at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:152)
                         W      at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:119)
                         W      at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:202)
                      ...

```

**Comment by karthik-119** [comment]
> @dkocher @karthik-119 Can you try with the fix from #800?

@hierynomus , let me try to verify the fix.

**Comment by karthik-119** [comment]
I realized that this project needs to be built with gradle which I'm not used to and have no correct configuration on my system. I'm afraid I can't verify the fix when it is still on issue branch.

Is there any possibility to build the project using maven?

**Comment by hierynomus** [comment]
There should be no need to set it up. You can use `./gradlew build` to build the project. This will use the Gradle wrapper. There is no Maven build files included

**Comment by karthik-119** [comment]
Yes, I did the same but see errors (Java version: 1.8):
<img width="956" alt="image" src="https://github.com/hierynomus/smbj/assets/30727836/d4218dac-9df3-4138-b5bf-352ef6ba044c">

**Comment by hierynomus** [comment]
For building you need to use Java11 (or higher)

**Comment by karthik-119** [comment]
Thanks, I'm able to build project with Java 11, can you please update Readme, it still says Java 7? thanks.

I'll test the jar and update results here.

**Comment by karthik-119** [comment]
Verified and can still see same NullPointerException.
```
java.lang.NullPointerException
	at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKey(SMBSessionBuilder.java:324)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKeys(SMBSessionBuilder.java:290)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:174)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:152)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:119)
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:202)
```

**Comment by HubertOT** [comment]
Indeed any update on this issue?
As karthik-119 mentioned within method **derivedKeys** the _sessionFlags_ are checked for _anonymous_ (SMB2_SESSION_FLAG_IS_NULL) or _guest_ (SMB2_SESSION_FLAG_IS_GUEST) login request. 

Using SMBj 0.11.5 when an anonymous logon (no username nor password set) was done the _sessionFlag_  SMB2_SESSION_FLAG_IS_GUEST was set and the logon succeeded. Doubt if this was for the correct reason, would have expected that _sessionFlag_ "SMB2_SESSION_FLAG_IS_NULL" was set instead of "SMB2_SESSION_FLAG_IS_GUEST".
However with SMBj 0.12.x it fails as none of these sessionFlags are set, hence for signing it is tried to set the deriveKey, based on context. The context however does not contain a sessionKey as it's an anonymous login which is not able to sign or encrypt.

**Comment by dsforcam** [comment]
Any update on this?

**Comment by dsforcam** [comment]
Any update on this?

**Comment by dsforcam** [comment]
Any update on this?

**Comment by bio-mjukis** [comment]
There is an open PR for this issue: https://github.com/hierynomus/smbj/pull/800
Does anyone know a workaround for this issue (to use until the PR is merged to master)?

We can't get unauthenticated samba connection to work using smbj 0.13.0 due to this issue. Here is a stack trace:

` java.lang.NullPointerException: Cannot invoke "javax.crypto.SecretKey.getEncoded()" because "derivationKey" is null
        at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKey(SMBSessionBuilder.java:324)
        at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKeys(SMBSessionBuilder.java:290)
        at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:174)
        at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:152)
        at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:119)
        at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:202)`

**Comment by hierynomus** [comment]
Fixed now and released in 0.14.0

**Comment by bio-mjukis** [comment]
For us using AuthenticationContext.anonymous() we still get same exception in 0.14.0 (se my previous post Nov 8)

AuthenticationContext.guest() does work in both 0.11.5 and 0.14. I don't know Samba much but perhaps we should just go with the guest-login instead. Does anyone have any thought on this?

**Comment by bubbleguuum** [comment]
Confirming issue persists as described in above post with anonymous logins (using Samba as well, not tested anonymous on other servers):

```
 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'byte[] javax.crypto.SecretKey.getEncoded()' on a null object reference
  at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKey(SMBSessionBuilder.java:324)
  at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKeys(SMBSessionBuilder.java:292)
  at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:174)
  at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:152)
  at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:119)
  at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:206)
```

 Will have to revert back to 0.11.5 (again) for that reason.

**Comment by HubertOT** [comment]
Unfortunately also for us smbj 0.14.0 does not resolves the anonymous authentication issue hence reverted back to smbj 0.11.5

**Comment by sujeetpaandey** [comment]
Is there any update on this? Facing the same error with **_SpnegoAuthenticator_** and Kerberos/GSS. Version 0.14.0. 

`java.lang.NullPointerException: Cannot invoke "javax.crypto.SecretKey.getEncoded()" because "derivationKey" is null

	at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKey(SMBSessionBuilder.java:324)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKeys(SMBSessionBuilder.java:290)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:174)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:119)
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:206)`
